In [23]:
## Dieses Model soll erkennen, ob Banknoten gefälscht sind 1 oder nicht 0
## Hier werden Keras Framework und ein gegebenes Dataset benutzt

import numpy as np
from numpy import genfromtxt

In [24]:
#load .txt file from computer
data = genfromtxt(r'C:\Users\junio\Desktop\OpenCV-master-v6_00\DATA\bank_note_data.txt', delimiter=',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [25]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [26]:
features = data[:, 0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [27]:
X =features
y = labels

In [28]:
#split into train or test sets
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [30]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [31]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [32]:
len(X)

1372

In [33]:
len(X_train)

919

In [34]:
len(X_test)

453

In [35]:
#Daten zwischen 0 und 1 skalieren
from sklearn.preprocessing import MinMaxScaler

In [36]:
scaler_object = MinMaxScaler()

In [37]:
#Skalierung trainieren
scaler_object.fit(X_train)

MinMaxScaler()

In [38]:
#X_train skalieren
scaled_X_train = scaler_object.transform(X_train)

In [39]:
#see max value
scaled_X_train.max()

1.0000000000000002

In [40]:
#X_test skalieren
scaled_X_test = scaler_object.transform(X_test)

In [41]:
#see max value
scaled_X_test.max()

1.02679563427227

In [42]:
### Keras
from keras.models import Sequential
from keras.layers import Dense

In [44]:
#create a keras model
model = Sequential()

#first input layers
model.add(Dense(4, input_dim=4, activation='relu'))
#second layer (1 hidden layer)
model.add(Dense(8, activation='relu'))
#third layer, output layer
model.add(Dense(1, activation='sigmoid'))

In [45]:
#compile/prepare the model for training
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [46]:
#train the model 50 times (epochs)
#verbose: 'auto', 0, 1, or 2. Verbosity mode.
#0 = silent, 1 = progress bar, 2 = one line per epoch
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 0s - loss: 0.6912 - accuracy: 0.5909
Epoch 2/50
29/29 - 0s - loss: 0.6891 - accuracy: 0.6007
Epoch 3/50
29/29 - 0s - loss: 0.6861 - accuracy: 0.6072
Epoch 4/50
29/29 - 0s - loss: 0.6817 - accuracy: 0.6159
Epoch 5/50
29/29 - 0s - loss: 0.6753 - accuracy: 0.6289
Epoch 6/50
29/29 - 0s - loss: 0.6665 - accuracy: 0.6453
Epoch 7/50
29/29 - 0s - loss: 0.6589 - accuracy: 0.6464
Epoch 8/50
29/29 - 0s - loss: 0.6507 - accuracy: 0.6529
Epoch 9/50
29/29 - 0s - loss: 0.6420 - accuracy: 0.6670
Epoch 10/50
29/29 - 0s - loss: 0.6324 - accuracy: 0.6768
Epoch 11/50
29/29 - 0s - loss: 0.6228 - accuracy: 0.6812
Epoch 12/50
29/29 - 0s - loss: 0.6127 - accuracy: 0.6888
Epoch 13/50
29/29 - 0s - loss: 0.6024 - accuracy: 0.6921
Epoch 14/50
29/29 - 0s - loss: 0.5919 - accuracy: 0.7051
Epoch 15/50
29/29 - 0s - loss: 0.5815 - accuracy: 0.7040
Epoch 16/50
29/29 - 0s - loss: 0.5705 - accuracy: 0.7095
Epoch 17/50
29/29 - 0s - loss: 0.5599 - accuracy: 0.7018
Epoch 18/50
29/29 - 0s - loss: 0.5494 - 

In [48]:
#test the model with scaled test sets
prediction = (model.predict(scaled_X_test) > 0.5).astype("int32")

In [49]:
model.metrics_names

['loss', 'accuracy']

In [50]:
from sklearn.metrics import confusion_matrix, classification_report

In [51]:
#confusion matrix to compare with the y_test set
confusion_matrix(y_test, prediction)

array([[241,  16],
       [ 43, 153]], dtype=int64)

In [52]:
#classification report
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

         0.0       0.85      0.94      0.89       257
         1.0       0.91      0.78      0.84       196

    accuracy                           0.87       453
   macro avg       0.88      0.86      0.86       453
weighted avg       0.87      0.87      0.87       453



In [53]:
#save the model
model.save('modelprojekt1.h5')

In [54]:
#load the model for deploying
from keras.models import load_model

new_model = load_model('modelprojekt1.h5')

In [56]:
(new_model.predict(X_test) > 0.5).astype("int32")

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    